In [1]:
import numpy as np


In [24]:
#Lecture d'un fichier text
iris=np.genfromtxt("iris.csv", delimiter=";", skip_header=True)
iris

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [25]:
#moyenne des colonnes
iris_moyenne_col=np.mean(iris,axis=0)
iris_moyenne_col

array([5.84333333, 3.05733333, 3.758     , 1.19933333, 2.        ])

In [13]:
#moyenne des lignes
iris_moyenne_ligne=np.mean(iris,axis=1)
iris_moyenne_ligne

array([2.24, 2.1 , 2.08, 2.08, 2.24, 2.48, 2.14, 2.22, 1.98, 2.12, 2.36,
       2.2 , 2.06, 1.9 , 2.44, 2.6 , 2.4 , 2.26, 2.5 , 2.34, 2.34, 2.34,
       2.08, 2.32, 2.26, 2.16, 2.28, 2.28, 2.24, 2.14, 2.14, 2.34, 2.38,
       2.46, 2.14, 2.12, 2.3 , 2.2 , 1.98, 2.24, 2.22, 1.88, 2.02, 2.34,
       2.44, 2.1 , 2.34, 2.08, 2.34, 2.18, 3.66, 3.52, 3.68, 3.02, 3.48,
       3.26, 3.58, 2.72, 3.48, 3.04, 2.7 , 3.32, 3.04, 3.42, 3.08, 3.52,
       3.32, 3.12, 3.28, 3.02, 3.54, 3.24, 3.44, 3.36, 3.38, 3.48, 3.56,
       3.68, 3.38, 2.96, 2.96, 2.92, 3.12, 3.48, 3.28, 3.5 , 3.6 , 3.26,
       3.2 , 3.06, 3.14, 3.42, 3.12, 2.72, 3.16, 3.22, 3.22, 3.34, 2.74,
       3.18, 4.22, 3.7 , 4.22, 3.92, 4.1 , 4.46, 3.32, 4.26, 3.96, 4.48,
       3.96, 3.86, 4.08, 3.64, 3.82, 4.04, 3.96, 4.68, 4.5 , 3.54, 4.22,
       3.66, 4.44, 3.74, 4.16, 4.24, 3.72, 3.76, 3.98, 4.12, 4.24, 4.62,
       4.  , 3.74, 3.74, 4.42, 4.14, 3.96, 3.72, 4.1 , 4.16, 4.08, 3.7 ,
       4.24, 4.24, 4.04, 3.74, 3.94, 4.06, 3.76])

In [26]:
#insérer une autre ligne: moyenne des colonnes
np.insert(iris,iris.shape[0],iris_moyenne_col,axis=0)

array([[5.1       , 3.5       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.        , 1.4       , 0.2       , 1.        ],
       [4.7       , 3.2       , 1.3       , 0.2       , 1.        ],
       [4.6       , 3.1       , 1.5       , 0.2       , 1.        ],
       [5.        , 3.6       , 1.4       , 0.2       , 1.        ],
       [5.4       , 3.9       , 1.7       , 0.4       , 1.        ],
       [4.6       , 3.4       , 1.4       , 0.3       , 1.        ],
       [5.        , 3.4       , 1.5       , 0.2       , 1.        ],
       [4.4       , 2.9       , 1.4       , 0.2       , 1.        ],
       [4.9       , 3.1       , 1.5       , 0.1       , 1.        ],
       [5.4       , 3.7       , 1.5       , 0.2       , 1.        ],
       [4.8       , 3.4       , 1.6       , 0.2       , 1.        ],
       [4.8       , 3.        , 1.4       , 0.1       , 1.        ],
       [4.3       , 3.        , 1.1       , 0.1       , 1.        ],
       [5.8       , 4.        , 1.

In [22]:
#insérer une autre colonne: moyenne des lignes
#np.insert(iris,iris.shape[1],iris_moyenne_ligne,axis=1)

In [28]:
#sauvegarder un fichier 
np.savetxt("save_iris.csv",iris,delimiter=";")

In [33]:
#selection une portion du tableau avec une condition
#appliquer le masque
print(iris[iris>5],iris[iris<2].shape[0])

[5.1 5.4 5.4 5.8 5.7 5.4 5.1 5.7 5.1 5.4 5.1 5.1 5.2 5.2 5.4 5.2 5.5 5.5
 5.1 5.1 5.1 5.3 7.  6.4 6.9 5.5 6.5 5.7 6.3 6.6 5.2 5.9 6.  6.1 5.6 6.7
 5.6 5.8 6.2 5.6 5.9 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.
 5.1 5.4 6.  6.7 6.3 5.6 5.5 5.5 6.1 5.8 5.6 5.7 5.7 6.2 5.1 5.7 6.3 6.
 5.8 5.1 7.1 5.9 6.3 5.6 6.5 5.8 7.6 6.6 7.3 6.3 6.7 5.8 7.2 6.1 6.5 5.1
 6.4 5.3 6.8 5.5 5.7 5.8 5.1 6.4 5.3 6.5 5.5 7.7 6.7 7.7 6.9 6.  6.9 5.7
 5.6 7.7 6.7 6.3 6.7 5.7 7.2 6.  6.2 6.1 6.4 5.6 7.2 5.8 7.4 6.1 7.9 6.4
 6.4 5.6 6.3 5.1 6.1 5.6 7.7 6.1 6.3 5.6 6.4 5.5 6.  6.9 5.4 6.7 5.6 6.9
 5.1 5.8 5.1 6.8 5.9 6.7 5.7 6.7 5.2 6.3 6.5 5.2 6.2 5.4 5.9 5.1] 221


In [34]:
iris>5

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, Fal

In [42]:
#appliquer le masque sur une colonne
iris2=iris[iris[:,4]>2]
print(iris2,iris2.shape[0])

[[6.3 3.3 6.  2.5 3. ]
 [5.8 2.7 5.1 1.9 3. ]
 [7.1 3.  5.9 2.1 3. ]
 [6.3 2.9 5.6 1.8 3. ]
 [6.5 3.  5.8 2.2 3. ]
 [7.6 3.  6.6 2.1 3. ]
 [4.9 2.5 4.5 1.7 3. ]
 [7.3 2.9 6.3 1.8 3. ]
 [6.7 2.5 5.8 1.8 3. ]
 [7.2 3.6 6.1 2.5 3. ]
 [6.5 3.2 5.1 2.  3. ]
 [6.4 2.7 5.3 1.9 3. ]
 [6.8 3.  5.5 2.1 3. ]
 [5.7 2.5 5.  2.  3. ]
 [5.8 2.8 5.1 2.4 3. ]
 [6.4 3.2 5.3 2.3 3. ]
 [6.5 3.  5.5 1.8 3. ]
 [7.7 3.8 6.7 2.2 3. ]
 [7.7 2.6 6.9 2.3 3. ]
 [6.  2.2 5.  1.5 3. ]
 [6.9 3.2 5.7 2.3 3. ]
 [5.6 2.8 4.9 2.  3. ]
 [7.7 2.8 6.7 2.  3. ]
 [6.3 2.7 4.9 1.8 3. ]
 [6.7 3.3 5.7 2.1 3. ]
 [7.2 3.2 6.  1.8 3. ]
 [6.2 2.8 4.8 1.8 3. ]
 [6.1 3.  4.9 1.8 3. ]
 [6.4 2.8 5.6 2.1 3. ]
 [7.2 3.  5.8 1.6 3. ]
 [7.4 2.8 6.1 1.9 3. ]
 [7.9 3.8 6.4 2.  3. ]
 [6.4 2.8 5.6 2.2 3. ]
 [6.3 2.8 5.1 1.5 3. ]
 [6.1 2.6 5.6 1.4 3. ]
 [7.7 3.  6.1 2.3 3. ]
 [6.3 3.4 5.6 2.4 3. ]
 [6.4 3.1 5.5 1.8 3. ]
 [6.  3.  4.8 1.8 3. ]
 [6.9 3.1 5.4 2.1 3. ]
 [6.7 3.1 5.6 2.4 3. ]
 [6.9 3.1 5.1 2.3 3. ]
 [5.8 2.7 5.1 1.9 3. ]
 [6.8 3.2 5

In [51]:
# Indexation Fantaisie:
tableau=np.array([1,2,3,4,5,6,7,8,9,10])
print(tableau[np.array([[4,8]])])
print(tableau[np.array([[4,8]])][0,1])
print(tableau[4])

[[5 9]]
9
5


In [54]:
#selection une tranche d'éléments
# tableau à 1 dimension
tableau[:3]
tableau[2:]
tableau[1:5]

array([2, 3, 4, 5])

In [63]:
tableau[:3]

array([1, 2, 3])

In [62]:
tableau[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
#tous les éléments avec un pas de 2
tableau[::2]

array([1, 3, 5, 7, 9])

In [58]:
# tableau à 2 dimensions 
iris[:2,:3]


array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4]])

In [60]:
#toutes les lignes à partir de l'index 148  et toutes les colonnes à partir de la 4eme
iris[148:,3:]

array([[2.3, 3. ],
       [1.8, 3. ]])

In [61]:
#toutes les colonnes de la ligne 5
iris[4,:]

array([5. , 3.6, 1.4, 0.2, 1. ])

In [64]:
#la dernière ligne
iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

In [66]:
# les opérations mathématiques
monTableau=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.add(monTableau,10)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [67]:
np.multiply(monTableau,3)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [70]:
monTableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
monTableau1=np.array([[11,12,13],[14,15,16],[17,18,19]])
np.multiply(monTableau,monTableau1)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [72]:
# Les fonctions d'agrégations
# somme de tous les éléments 
print(np.sum(iris))

2378.7


In [76]:
# somme par colonnes axis=0 et ligne axis=1
print("somme par colonne:",np.sum(iris,axis=0))
print("somme par ligne:", np.sum(iris,axis=1))

somme par colonne: [876.5 458.6 563.7 179.9 300. ]
somme par ligne: [11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [81]:
print("moyenne par colonne:",np.mean(iris,axis=0))
print("ecart type par colonne:", np.std(iris,axis=0))
print("max par colonne",np.max(iris,axis=0))

moyenne par colonne: [5.84333333 3.05733333 3.758      1.19933333 2.        ]
ecart type par colonne: [0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]
max par colonne [7.9 4.4 6.9 2.5 3. ]


In [85]:
iris3=iris[iris[:,4]==3]
iris3
print(np.mean(iris[iris[:,4]==3],axis=0))

[6.588 2.974 5.552 2.026 3.   ]


In [87]:
# la transposée 
iris.T.shape

(5, 150)

In [88]:
# Ajouter des éléments dans un tableau
np.append(monTableau,[40,41,51])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 41, 51])

In [89]:
np.insert(iris,1,[10,10,10,10,10],axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [90]:
#supprimer une ligne
np.delete(iris,1,axis=0)

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3

In [91]:
#supprimer plusieurs éléments en indiquant leurs indices
np.delete(iris,[2,3,6],axis=0)

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4

In [96]:
np.insert(monTableau,1,10)

array([ 1, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [97]:
monTableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.delete(monTableau,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [98]:
monTableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
iris.shape

(150, 5)

In [127]:
tableauSplit=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])

print(np.split(tableauSplit, [3, 4]))

[array([1, 2, 3]), array([4]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])]


In [128]:
tableau1, tableau2, tableau3 = np.split(tableauSplit, [3, 4])
print(tableau1,tableau2, tableau3)

[1 2 3] [4] [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30]


In [129]:
monTableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
np.split(monTableau,[3])

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32)]

In [132]:
np.vsplit(monTableau,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [135]:
np.hsplit(monTableau,[2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [137]:
#Concaténer et Combiner des tableaux:
t1=np.array([1,2,3,4,5,6,7,8,9])
t2=np.array([10,11,12])
t3=np.array([13,14,15])
np.concatenate([t1,t2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
#vstack() empile les talbeaus verticalement
tableau1=np.array([[1,2,3],[4,5,6]])
tableau2=np.array([45,46,47])
tableau3=np.array([[60,50],[61,51]])
np.vstack([tableau1,tableau2])
 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [45, 46, 47]])

In [145]:
tableau1

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
#hstack() empile les tableaux horizontalement
np.hstack([tableau1,tableau3])

array([[ 1,  2,  3, 60, 50],
       [ 4,  5,  6, 61, 51]])